### PR TITLE
add .node-version to rep node version in parallel to .ruby-version

### PR DESCRIPTION
**Pull request by davidalpert**

### CODE REVIEW

**Comment by meg-gutshall** [comment]
Hey David! We're using yarn for this project. 👍

**Comment by davidalpert** [comment]
when I use `yarn` I still need to know which version of `node` to work with :D

**Comment by meg-gutshall** [comment]
Yeah, I realized that after I closed this. My bad. Lol!

**Comment by meg-gutshall** [comment]
If you change the version to match what's in the README, I'll merge it in!

**Pull request merged**
